# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b428f0b396fbcadbe4c45768d83798e56b28c0bf044b1dfbff204a35e8dc79de905c716727c27b51158b2e7f9e71c59c57ac4a6b47f353e0c6743d191e04e676

test:
  secret_key_base: 523e65d894082ddef83df7cb97ff00ce43fd390d7cd65bc9f8ac959df8567a75a217f064a93fbad07cce9af4bafe7ca8bb8fd15318b02fe80b38e6c9469e5fed

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
